name: wx_image_editor
description: A WeChat like image editor.
version: 0.0.2
repository: https://github.com/weichengwu/wx_image_editor

platforms:
  android:
  ios:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.weichengwu.wx_image_editor
        pluginClass: WxImageEditorPlugin
      ios:
        pluginClass: WxImageEditorPlugin